#!/usr/bin/env bash
# dependencies
#   sxhkd         :   mandatory for bspwm
#   rofi          :   rofi-themes are also neccessary https://github.com/adi1090x/rofi
#   polybar       :   fancy statusbar
#   picom         :   animations and eye-candy
#   autowall      :   simple program to get wallpapers from WallHaven
#   feh           :   set a wallpaper
#   dunst         :   see notifications
#   flameshot     :   take screenshots easly
#   lxsession     :   polkit is necessary for programs requiring root access
#   pamixer       :   increase, decrease volume with keyboard
#   slock         :   lock your screen in a lightweight way (source code)
#   xss-lock      :   autolock screen
#   xsetroot      :   it is needed
#   wmname        :   this solves problems with Java GUI applications not displaying correctly
#
#   This is just the main entry
#   explore the rest of the code to automatically understand
#   how things work. This is how it should be done, and
#   even this can obviously be done MUCH better.

# utils should be loaded before anything else

shopt -s globstar
source "$HOME/.config/bspwm/config"
source "$BASE_DIR/src/functions.sh"

# Set environment variables
export PATH="$BASE_DIR/src:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'

# DO NOT REMOVE ---------------------------------------------------
run sxhkd -c "$GLOBALS_DIR/sxhkd/sxhkdrc"
# -----------------------------------------------------------------
# I put this here because if anything fails, at least this is ok and
# you can safely logout, run a terminal, open a browser, or whatever

# source "$HOME/.config/bspwm/bin/Theme.sh"
source "$SRC_DIR/autorun.sh"
source "$SRC_DIR/monitor.sh"
source "$SRC_DIR/global-bspwm.sh"
source "$SRC_DIR/misc.sh"
source "$THEME_DIR/config.sh"
source "$SRC_DIR/libinput.sh"
source "$BIN_DIR/loader.sh"

shopt -u globstar

dunstify -a "Gwyn" "Gwyn" "Theme ${THEME_NAME} loaded"
