; ____       _       _
;|  _ \ ___ | |_   _| |__   __ _ _ __
;| |_) / _ \| | | | | '_ \ / _` | '__|    z0mbi3
;|  __/ (_) | | |_| | |_) | (_| | |       https://github.com/gh0stzk/dotfiles
;|_|   \___/|_|\__, |_.__/ \__,_|_|       z0mbi3.zk@protonmail.com
;               |___/

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = ../../../globals/polybar/system.ini
include-file = modules.ini


[color]

dark = #161616
light = #dde1e6
white = #f2f4f8
red = #ff1477
pink = #ff7eb6
purple = #be95ff
blue = #33b1ff
cyan = #3ddbd9
teal = #08bdba
green = #42be65
lime = #24a148
yellow = #f1c21b
amber = #eb6200
orange = #ff832b
brown = #8a3800
grey = #525252
indigo = #78a9ff
blue-gray = #878d96

bg = "${color.dark}"
bg-alt = "${color.light}"
fg = "${color.light}"

bg-bar = #AA161616
fg-bar = "${color.light}"

accent = "${color.indigo}"
fg-focused = "${color.dark}"
bg-focused = "${color.accent}"
fg-unfocused = "${color.fg}"
bg-unfocused = "${color.bg}"
underline-occupied = "${color.accent}"

pad=2

;; =======================================
;; BASE SETTINGS (Shared across all bars)
;; =======================================
[bar/base]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true

height = 27
offset-y = 4

background = ${color.bg-bar}
foreground = ${color.fg-bar}

radius = 8

line-size = 2
line-color = ${color.blue}

border-size = 0
border-color = ${color.bg}

padding-left = 0
padding-right = 0

module-margin-left = 0.2
module-margin-right = 0.2

font-0 = "FiraCode Nerd Font:size=9;2"
font-1 = "Material Design Icons Desktop:size=12;4"
font-2 = "Material Design Icons Desktop:size=9;3"
font-3 = "Font Awesome 6 Free Solid:size=8;3"

separator =
dim-value = 1.0

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[bar/left]
inherit = bar/base
width = 16.48%
offset-x = 0.5%
modules-left = bspwm

[bar/center]
inherit = bar/base
width = 25%
offset-x = 28.5%
padding-left = 2
padding-right = 2
modules-left = sep title
modules-right= date sep

[bar/right]
inherit = bar/base
width = 35%
offset-x = 64.5%
modules-left = sep pulseaudio sep2 filesystem sep2 cpu_bar sep temperature sep2 memory_bar
modules-right = tray sep2 battery sep

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = true
